on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download Project References
        run: |
          sudo mkdir --parents /tmp/dependencies/

          # Install dependencies via apt
          #   curl: required by DepotDownloader installation
          #   unzip: required by DepotDownloader installation
          sudo apt-get update
          sudo apt-get install --assume-yes curl unzip

          # Install DepotDownloader
          sudo curl -JOL https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_3.4.0/DepotDownloader-linux-x64.zip
          sudo unzip DepotDownloader-linux-x64.zip -d /tmp/dependencies/DepotDownloader/
          sudo mv /tmp/dependencies/DepotDownloader/DepotDownloader /usr/local/bin/depotdownloader
          sudo chmod +x /usr/local/bin/depotdownloader

          # Download References
          ./download-references.sh

      - name: Build Solution
        run: |
          dotnet build Rust.PreventBlueprintWipes.sln \
            --configuration Release \
            --disable-build-servers

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Rust.PreventBlueprintWipes-Artifacts.zip
          path: |
            Rust.PreventBlueprintWipes/bin/Release/net48/